version: "3.3"
services:
  zookeeper:
    image: "wurstmeister/zookeeper:3.4.6"
    ports:
      - "2181:2181"
  kafka:
    image: "wurstmeister/kafka:2.12-2.2.0"
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  repo:
    build:
      context: .
    depends_on:
      - kafka
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info
